repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, docs, test, ci, refactor]

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black
        # args: [--line-length=79]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        # args: [
        #   --statistics,
        #   --max-line-length=88
        # ]
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.8'
    hooks:
    - id: bandit
      args: ["-r", "-x", '*/tests/*', "."]