version: '3.9'

services:
  mongodb:
    image: mongo:5.0.14
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart: always

  api:
    build: 
      context: .
    ports:
      - 5000:5000
    environment:
      - FLASK_DEBUG=development
      - MONGODB_DB=users
      - MONGODB_HOST=mongodb
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
    restart: always
    depends_on:
      - mongodb
    volumes:
      - ./api/:/app/api
