version: '3.9'

services:
  mongodb:
    image: mongo:5.0.14
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart: always

  api:
    build: 
      context: .
    ports:
      - 5000:5000
    environment:
      - FLASK_DEBUG=development
      - MONGODB_DB=users
      - MONGODB_HOST=mongodb
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
    restart: always
    depends_on:
      - mongodb
    volumes:
      - ./api/:/app/api
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  grafana:  
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "472"
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./monitoring/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    env_file:
      - ./monitoring/config.monitoring